spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
   hikari:
    driverClassName: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/batch
    username: root
    password: 1234

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always


