spring:
  profiles:
    active: test

  application:
    name: toy1

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 8ukYwwU18_bV8hd2kDVU
            client-secret: ChXfsV1lT3
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

          kakao:
            client-id: d70c58c2248ead9893536e3ef18bd7f9
            client-secret: 84E7v6d6FuIZUfHLhwir40YhNQIwJdxf
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post  #kakao POST 대신 client_secret_post, client_secret_basic, none 이 제공된다고 합니다.
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #default Naming
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true



  # header value is default response header message
jwt:
  secretKey: asdkl12klm3dksofjn23iun32i4fnbkjsadnfjksdafniuawefbn23kjbf2k3bwkajerfbiwfehb32f

  access:
    expiration: 3600000 # 1시간  (60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #   2주  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh


